### ISSUE TITLE
Invalid names are allowed when building a plugin

### ISSUE THREAD

**Issue by dccioata** [tcorbettclark/encapsia-cli#18]
Steps to Reproduce:
1. In the plugin.toml file set an invalid name (e.g. containing underscores)
2. Build the plugin

Expected Behavior:
Invalid plugin names are prevented and the plugin is not built

Current Behavior:
The tar.gz file is created (the plugin is built)

**Comment by petrem** [comment]
Agreed, except the particular example is incorrect: underscores are allowed. Allowed namespaces are matching regex `re.compile(r"^(?!pg_)[a-z][a-z0-9_]*$", re.ASCII)`, excluding any of: `"analytics core operational pluginsmanager public reporting uploads v1 dbctl documentation fixture_manager tmp".split()`

**Comment by dccioata** [comment]
The example with underscore didn't serve the web files via nginx back then (thus not able to use plugins with underscore in their names) ... Considering the underscore problem is fixed in nginx, I agree now it just needs to respect the regex above.

**Comment by tcorbettclark** [comment]
There is the wider question of validation, beyond just checking the name.

Possibly this should be done in encapsia-api, and encapsia-cli should use e.g. encapsia-api's PluginMaker class.

**Comment by dccioata** [comment]
It makes sense now to implement these kind of validations in encapsia-api and other clients (for example, encapsia-cli) will use them.
Should we close this issue and raise another issue on encapsia-api for keeping track of needed validations?

Considering icepluginsmanager currently has his own logic of plugin name validation, maybe, in the future, we could reuse the name logic one which will be implemented in encapsia-api.

**Comment by tcorbettclark** [comment]
Good idea Dani

Here: https://github.com/tcorbettclark/encapsia-api/issues/23

PS Hope you are enjoying fatherhood! :-)

**Comment by dccioata** [comment]
Closed this issue as another one was raised on encapsia-api (see above).
