### ISSUE TITLE
uninstall plugin causes traceback

### ISSUE THREAD

**Issue by tstone3** [tcorbettclark/encapsia-cli#19]
Steps to reproduce:
uninstall a plugin using encapsia plugins --host inscro1 uninstall tg001tokengenerator

Expected Behaviour:
Plugin is uninstalled successfully

Actual Behaviour
Output displays "Uninstalling tg001tokengenerator...Done" but then displays traceback KeyError:'id'

![image](https://user-images.githubusercontent.com/61496165/75329669-ec7a1e00-5877-11ea-921f-ab39449660d6.png)

**Comment by tcorbettclark** [comment]
Fixed by earlier changes. At least, no longer reproducible. Closing....
