### ISSUE TITLE
semver bug

### ISSUE THREAD

**Issue by RattyBiscuit** [tcorbettclark/encapsia-cli#46]
The full semver syntax is not supported, only the major.minor.patch

The pre-release / build metadata is not supported

I created a plugin using the semver 1.0.0-dev.1 and it failed, however removing the pre-release section of the file name succeeded

`semver` library should be used instead of the regex:

`m = re.match(r"plugin-([^-]*)-([^-]*).tar.gz", full_name)`

**Comment by tcorbettclark** [comment]
Fixedin 0.3.2
