### ISSUE TITLE
Installing groups of plugins with one command

### ISSUE THREAD

**Issue by tcorbettclark** [tcorbettclark/encapsia-cli#87]
There doesn't seem to be a neat way to add/update plugins on a server based on an S3-bucket using the encapsia_cli

e.g. we have the latest releases in the "production" S3 Insight folder(s) which I want to install onto a server. 

Something like 
$ encapsia --host encval-v15-uat plugins --s3-bucket encapsia-plugins/cmedcro/standards/production/insights install

**Comment by petrem** [comment]
I'd prefer an explicit option, similar to `--versions` and `--lastest-existing` (which is a bit off-key, maybe):

```
$ encapsia --host foo --s3-bucket path-to-s3 install --latest-available
```

or `--all-from-s3` or similar.
